create docker build of standalone output

diff --git a/front-end/Dockerfile b/front-end/Dockerfile
--- a/front-end/Dockerfile
+++ b/front-end/Dockerfile
@@ -1,21 +1,69 @@
-FROM node:18.17.1-alpine3.18
-# Setting working directory. All the path will be relative to WORKDIR
-WORKDIR /usr/src/app
-# Installing dependencies
-COPY package*.json ./
-RUN npm install
-# Copying source files
-COPY . .
-# Building app
-RUN npm run build
-EXPOSE 3000
-# Running the app
-CMD [ "npm", "start" ]
+FROM node:18.17.1-alpine3.18 AS base
 
-# TODO
-# Build static and public files (e.g. images) should be put somewhere like S3 for CDN/Cloudfront to serve
-# Only bring into the container the final NextJS app - standalone mode?
-# Multistage docker build - Build the app in standalone mode in the first stage
-# Final stage - bring over what is needed to the final stage and run directly
-# https://www.ryanmr.com/posts/next-standalone-mode
-# https://nextjs.org/docs/app/api-reference/next-config-js/output
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+VOLUME ./artifact
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+# RUN yarn build
+
+# If using npm comment out above and use below instead
+RUN npm run build
+
+RUN cp -r /app/.next/static artifact
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
+EXPOSE 3000
+
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+
+CMD ["node", "server.js"]
